name: AndroidBuild

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.0
        with:
          name: Tweetio.apk
          path: app/build/outputs/apk/app-debug.apk
